### ISSUE TITLE
Rename `Windows GMSA` chart to `Windows gMSA` to be consistent with other gMSA charts

### ISSUE THREAD

**Issue by markusewalker** [rancher/Rancher-Plugin-gMSA#19]
**Is your feature request related to a problem? Please describe.**

The Windows gMSA chart is currently stylized as `Windows GMSA` as seen below:

<img width="1215" alt="image" src="https://github.com/rancher/dashboard/assets/52591819/37d7e6c0-0a6d-47ec-9411-7b2884c0c70c">

With the new gMSA charts being introduced, it is inconsistent with the stylizing of the other gMSA charts.

**Describe the solution you'd like**

To be consistent, we should change this to read as `Windows gMSA`. Additionally, this means the chart description and other locations in the chart need to be updated to `Windows gMSA` as well.

**Comment by aiyengar2** [comment]
Testable, released in `v0.0.2`

**Comment by markusewalker** [comment]
Validated that this is addressed:

<img width="1261" alt="image" src="https://github.com/rancher/Rancher-Plugin-gMSA/assets/52591819/ce063927-7e64-4a26-8f6b-7f7eef3bb76b">

Closing issue.
