### ISSUE TITLE
when deploying daemonset that uses securityContext with gmsaCredentialSpec + secret, `whoami /UPN` gives an error `ERROR: Unable to get User Principal Name (UPN) as the current logged-on user is not a domain user.`

### ISSUE THREAD

**Issue by slickwarren** [rancher/Rancher-Plugin-gMSA#25]
**Rancher Server Setup**
- Rancher version: v2.7.7

**Information about the Cluster**
- Kubernetes version: v1.26.8+rke2r1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): rke2, custom using azure VMs

**Describe the bug**

**To Reproduce**
 
* Follow test plan, deploying an rke2 custom cluster with 4 windows nodes
* following step 19, deploy a gmsaCredentialSpec according to your setup
* deploy a secret that authenticates with your setup
* deploy a daemonset that uses `securityContext.windowsOptions.gmsaCredentialSpecName` which matches what you've setup in step 19
* wait for the daemonset to get to an active state
* ssh into the pod(s) running from the daemonset and ensure `whoami /UPN` returns a domain authenticated user

**Result**
`ERROR: Unable to get User Principal Name (UPN) as the current logged-on user is not a domain user.`

**Expected Result**

`whoami /UPN` returns a domain authenticated user

**Screenshots**

**Additional context**

spoke offilne, and this is likely an issue with the gmsaCredentialSpec (i.e. a typo)

gmsaCredentialSpec:
```
apiVersion: windows.k8s.io/v1
credspec:
  ActiveDirectoryConfig:
    GroupManagedServiceAccounts:
      - Name: GMSA1
        Scope: ad
      - Name: GMSA1
        Scope: <subdomain>.ad.com
    HostAccountConfig:
      PluginGUID: '{<guid>}'
      PluginInput: cattle-windows-gmsa-system:rancher-domain-user-credentials
      PortableCcgVersion: '1'
  CmsPlugins:
    - ActiveDirectory
  DomainJoinConfig:
    DnsName: <subdomain>.ad.com
    DnsTreeName: <subdomain>.ad.com
    Guid: <guid>
    MachineAccountName: GMSA1
    NetBiosName: ad
    Sid: <sid>
kind: GMSACredentialSpec
metadata:
  annotations:
...
  creationTimestamp: '2023-10-25T18:05:45Z'
  generation: 4
...
    - apiVersion: windows.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:credspec:
          f:ActiveDirectoryConfig:
            f:HostAccountConfig:
              f:PluginInput: {}
          f:DomainJoinConfig:
            f:Guid: {}
      manager: agent
      operation: Update
      time: '2023-10-25T22:04:09Z'
  name: test-gmsa-spec
  resourceVersion: '151680'
  uid: <uid>
```

**Comment by aiyengar2** [comment]
Since the docs are being addressed in https://github.com/rancher/Rancher-Plugin-gMSA/pull/16, @slickwarren I'll move this issue back to test.

**Comment by markusewalker** [comment]
Validated that this is addressed. See below:

**ENVIRONMENT DETAILS**
- Rancher version: `v2.7.7`
- Rancher install: Docker

**TEST RESULTS**
|Scenario|Test Case|Result|
|---|---|---|
|1|Validate that a domain authenticated user is running on a deployed daemonset on supported Windows OSes|:white_check_mark:|

**VALIDATION STEPS**
1. Provisioned a downstream RKE2 v1.26.8+rke2r1 custom cluster w/Windows nodes (I had 3 etcd, 1 cp, 2 Linux workers, 4 Windows workers).
2. Navigated to Cluster explorer > cluster > Apps > Repositories.
3. Added the https://github.com/rancher/Rancher-Plugin-gMSA repo with the main branch.
4. Installed the Windows GMSA, Rancher gMSA CCG Plugin and Rancher gMSA Account Provider charts.
5. Created a GMSACredentialSpec + secret with my Azure AD information.
6. Deployed a daemonset to each of my 4 Windows worker environments.
7. Executed into each resulting shell and ran command `whoami /UPN`; the results were successful in returning a domain authenticated user.
