### ISSUE TITLE
Validate Rancher gMSA CCG Plugin Initial Implementation

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/Rancher-Plugin-gMSA#4]
This issue tracks the QA validation of the experimental Rancher gMSA CCG Plugin feature

As of October 23 2023, the `latest` images for both the `harrisonwaffel/gmsa-account-provider` and `harrisonwaffel/ccg-plugin-installer` are using commit `6047154`. In the near future these images will be moved into an official Rancher Docker hub repository.

**Comment by markusewalker** [comment]
This ticket has been validated in QA's internal, comprehensive test plan. Any sub-issues have been logged to not distract away from this issue.

@aiyengar2 I'm unable to close this issue, can you do so?
